text=input("Enter the sentence (use \\n for new lines): ")
text=text.replace("\\n","\n")
lines=text.splitlines()
words=text.split()
characters=len(text)
print("Lines:",len(lines))
print("Words:",len(words))
print("Characters:",characters)